site_name: Roboflow Inference
site_url: https://inference.roboflow.com/
site_author: Roboflow
site_description: Scalable, on-device computer vision deployment.
repo_name: roboflow/inference
repo_url: https://github.com/roboflow/inference
edit_uri: https://github.com/roboflow/inference/tree/main/docs
copyright: Roboflow 2023. All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roboflow
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/roboflow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/roboflow-ai/mycompany/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roboflow
  analytics:
    provider: google
    property: G-T0CED2YY8K
  version:
    default: 1.0

extra_css:
  - styles.css

nav:
  - Home:
    - Home: index.md
    - Get Started:
      - What is Inference?: quickstart/what_is_inference.md
      - What Devices Can I Use?: quickstart/devices.md
      - Configure an API Key: quickstart/configure_api_key.md
      - Run Your First Model: quickstart/run_a_model.md
      - Run a Fine-Tuned Model: quickstart/explore_models.md
    - Run a Model:
      - On an Image: quickstart/run_model_on_image.md
      - On a Video, Webcam or RTSP Stream: quickstart/run_model_on_rtsp_webcam.md
      - Over UDP: quickstart/run_model_over_udp.md
    - Use a Foundation Model:
      - What is a Foundation Model?: foundation/about.md
      - CLIP (Classification, Embeddings): foundation/clip.md
      - CogVLM (Multimodal Language Model): foundation/cogvlm.md
      - DocTR (OCR): foundation/doctr.md
      - Grounding DINO (Object Detection): foundation/grounding_dino.md
      - L2CS-Net (Gaze Detection): foundation/gaze.md
      - Segment Anything (Segmentation): foundation/sam.md
    - Reference:
      - Model Licensing: quickstart/licensing.md
      - Model Device Compatability: quickstart/compatability_matrix.md
      - Install Inference with Docker: quickstart/docker.md
      - Docker Configuration Options: quickstart/docker_configuration_options.md
      - SDK Reference: inference_sdk/http_client.md
      - Collect Data Without a Model: quickstart/stubs.md
  - HTTP API Reference:
    - API Reference: api.md
    - Back to Quickstart: /quickstart/what_is_inference/
  - Contribute:
    - Contribute to Inference: contributing.md
  - Changelog: https://github.com/roboflow/inference/releases

theme:
  name: 'material'
  logo: inference-icon.png
  favicon: inference-icon.png
  custom_dir: docs/theme
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: 'custom_theme'
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections
    - content.code.copy

plugins:
  - mkdocstrings
  - search
  - swagger-ui-tag
  - social:
      cards_layout_dir: docs/layouts
      cards_layout: custom

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_javascript:
  - "https://widget.kapa.ai/kapa-widget.bundle.js"
  - "javascript/init_kapa_widget.js"
