services:
  management-api:
    build:
      context: ${PWD}
      dockerfile: docker/dockerfiles/Dockerfile.stream_management_api
    ports:
      - "8080:8080"
    environment:
      - PROCESSES_MANAGER_CLIENT_PORT=7070
      - PROCESSES_MANAGER_CLIENT_HOST=stream_manager
    depends_on:
      - stream_manager
  stream_manager:
    build:
      context: ${PWD}
      dockerfile: docker/dockerfiles/Dockerfile.onnx.cpu.stream_manager
    environment:
      - STREAM_MANAGER_HOST=0.0.0.0
    ports:
      - "7070:7070"