name: mergeable

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check_if_branch_is_ahead_of_main:
    name: Check if branch is ahead of main
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch contains all commits from main via GitHub CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ "main" = "${{ github.head_ref || github.ref_name }}" ]; then
            echo "[OK] Merging to main";
            exit 0;
          fi
          response=$(gh api /repos/${{ github.repository }}/compare/main...${{ github.head_ref || github.ref_name }} )

          behind_by=$(echo "$response" | jq '.behind_by')
          status=$(echo "$response" | jq -r '.status')

          if [ "$behind_by" -eq 0 ] && [ "$status" = "ahead" ]; then
            echo "[OK] Selected branch is ahead of main and contains all commits."
          else
            echo "[FAIL] Selected branch does NOT meet the criteria."
            echo "Behind by: $behind_by"
            echo "Status: $status"
            exit 1
          fi
