name: E2E TEST - hosted inference - PRODUCTION

on:
  workflow_dispatch:
    inputs:
      skip_warmup:
        type: boolean
        description: "Do you want to skip services warmup?"
        default: false


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.test.unit.txt -r requirements/requirements.test.integration.txt
      - name: 📝 E2E test of HOSTED INFERENCE at 🚨 PRODUCTION 🚨 🔥🔥🔥🔥
        run:
          SKIP_WARMUP=${{ github.event.inputs.skip_warmup }} HOSTED_PLATFORM_TESTS_API_KEY=${{ secrets.LOAD_TEST_PRODUCTION_API_KEY }} HOSTED_PLATFORM_TESTS_PROJECT=roboflow-platform pytest tests/inference/hosted_platform_tests/
