name: INTEGRATION TESTS - Inference Server CPU x86

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  is_mergeable:
    outputs:
      mergeable_state: ${{ steps.mergeable_check.outputs.mergeable_state }}
    runs-on:
      labels: depot-ubuntu-22.04-8
      group: public-depot
    timeout-minutes: 15
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - name: Wait for mergeable state
        id: mergeable_check
        run: |
          if [ ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }} ]; then
            echo "mergeable_state=clean" >> "$GITHUB_OUTPUT"
          fi
  build:
    needs: is_mergeable
    if: ${{ github.event_name != 'pull_request' || needs.is_mergeable.outputs.mergeable_state == 'clean' }}
    if: ${{ !github.event.act }}
    runs-on:
      group: group8core
    timeout-minutes: 35

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.test.unit.txt -r requirements/requirements.test.integration.txt -r requirements/requirements.code_analysis.txt
      - name: 🔨 Build and Push Test Docker
        run: |
          docker pull roboflow/roboflow-inference-server-cpu:test
          docker build -t roboflow/roboflow-inference-server-cpu:test -f docker/dockerfiles/Dockerfile.onnx.cpu .
          docker push roboflow/roboflow-inference-server-cpu:test
      - name: 🔋 Start Test Docker
        run: |
          PORT=9101 INFERENCE_SERVER_REPO=roboflow-inference-server-cpu make start_test_docker_cpu
      - name: 🧪 Integration Tests of inference server [x86 CPU]
        run: |
          PORT=9101 SKIP_LMM_TEST=True API_KEY=${{ secrets.API_KEY }} asl_instance_segmentation_API_KEY=${{ secrets.ASL_INSTANCE_SEGMENTATION_API_KEY }} asl_poly_instance_seg_API_KEY=${{ secrets.ASL_POLY_INSTANCE_SEG_API_KEY }} bccd_favz3_API_KEY=${{ secrets.BCCD_FAVZ3_API_KEY }} bccd_i4nym_API_KEY=${{ secrets.BCCD_I4NYM_API_KEY }} cats_and_dogs_smnpl_API_KEY=${{ secrets.CATS_AND_DOGS_SMNPL_API_KEY }} coins_xaz9i_API_KEY=${{ secrets.COINS_XAZ9I_API_KEY }} melee_API_KEY=${{ secrets.MELEE_API_KEY }} yolonas_test_API_KEY=${{ secrets.YOLONAS_TEST_API_KEY }} python -m pytest tests/inference/integration_tests
          make stop_test_docker
