name: Static code analysis

on:
  pull_request:
    paths-ignore: "**/*.md"
    branches: [main]
  push:
    branches: [main]

jobs:
  is_mergeable:
    outputs:
      mergeable_state: ${{ steps.mergeable_check.outputs.mergeable_state }}
    runs-on:
      labels: depot-ubuntu-22.04-8
      group: public-depot
    timeout-minutes: 15
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - name: Wait for mergeable state
        id: mergeable_check
        run: |
          if [ ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }} ]; then
            echo "mergeable_state=clean" >> "$GITHUB_OUTPUT"
          fi
  build-dev-test:
    needs: is_mergeable
    if: ${{ github.event_name != 'pull_request' || needs.is_mergeable.outputs.mergeable_state == 'clean' }}
    runs-on:
      labels: depot-ubuntu-22.04-small
      group: public-depot
    timeout-minutes: 5
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install code analysis dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.code_analysis.txt
      - name: Check code quality
        run: |
          make check_code_quality
