name: TMP WORKFLOW DOCS BUILD

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install mkdocs-material
      - run: pip install "mkdocstrings[python]"
      - run: pip install "mkdocs-material[imaging]"
      - run: pip install "mkdocs-swagger-ui-tag"
      - run: pip install "mkdocs-gen-files"
      - run: pip install "mkdocs-literate-nav"
      - run: pip install "mkdocs-jupyter"
      - run: pip install -r requirements/requirements.docs.txt
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements/_requirements.txt -r requirements/requirements.cpu.txt -r requirements/requirements.sdk.http.txt -r requirements/requirements.test.unit.txt -r requirements/requirements.http.txt
      - run: python -m development.docs.build_block_docs
      - run: mkdocs gh-deploy --force